version: "2"
linters:
  default: all
  disable:
    - gomodguard # deprecated
    # These are disabled for now, primarily out of author preference
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct
    - godox
    - mnd
    - noinlineerr
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5

  exclusions:
    rules:
      - path: engine/crawler.go
        linters:
          - funlen
          - gocognit
          - nestif
      - path: internal/browser/profiles.go
        linters:
          - lll
      - path: logger.go
        linters:
          - gochecknoglobals
      - path: internal/pagetest/pagetest.go
        linters:
          - gosec
      - path: "cmd/(.+)/main.go"
        linters:
          - funlen
          - gochecknoglobals
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - goconst
          - lll
          - paralleltest

  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: camel
    revive:
      rules:
        - name: exported
          disabled: true
