name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build CLI tool
        run: make build.cli
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: virgo-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/virgo*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        run: ./scripts/release_notes.sh > ${{ github.workspace }}_RELEASE_NOTES.txt

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts/ -type f

      - name: Prepare for release
        run: |
          tar -czvf virgo-darwin-amd64.tar.gz artifacts/virgo-darwin-amd64/virgo
          tar -czvf virgo-darwin-arm64.tar.gz artifacts/virgo-darwin-arm64/virgo
          tar -czvf virgo-linux-amd64.tar.gz artifacts/virgo-linux-amd64/virgo
          tar -czvf virgo-linux-arm64.tar.gz artifacts/virgo-linux-arm64/virgo
          zip -r virgo-win-amd64.zip artifacts/virgo-windows-amd64/virgo
          zip -r virgo-win-arm64.zip artifacts/virgo-windows-arm64/virgo

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}_RELEASE_NOTES.txt
          draft: true
          files: |
            virgo-darwin-amd64.tar.gz
            virgo-darwin-arm64.tar.gz
            virgo-linux-amd64.tar.gz
            virgo-linux-arm64.tar.gz
            virgo-win-amd64.zip
            virgo-win-arm64.zip
